#' Marascuilo Test
#'
#' @param df A data.frame containing the raw data.
#' @param col_grupo Name of the column containing the categories/groups.
#' @param col_respuesta Name of the column with the responses (e.g., agree/disagree).
#' @param valor_exito The specific value in col_respuesta for which the proportion will be calculated.
#' @param alpha Significance level (default is 0.05).
#'
#' @return A data.frame with the results of the pairwise comparisons.
#' @export
#' @import purrr
marascuilo_test <- function(df, col_grupo, col_respuesta, valor_exito, alpha = 0.05) {
  
  # Generate a two-way contingency table
  tabla <- table(df[[col_grupo]], df[[col_respuesta]])
  n_j <- rowSums(tabla)
  x_j <- tabla[, as.character(valor_exito)]
  p_j <- x_j / n_j
  
  # Find the critical value in the chi-square distribution
  filas <- nrow(tabla)
  columnas <- ncol(tabla)
  grados_libertad <- (filas - 1) * (columnas - 1)
  chi_critico <- qchisq(1 - alpha, df = grados_libertad)
  
  # Generate all possible pairs without repetition
  nombres_grupos <- names(p_j)
  combinaciones <- combn(nombres_grupos, 2, simplify = FALSE)
  
  # map_dfr iterates over the list and directly returns the final data.frame
  resultados <- purrr::map_dfr(combinaciones, function(par) {
    g1 <- par[1]
    g2 <- par[2]
    
    # Get proportions and sample sizes
    p1 <- p_j[g1]
    p2 <- p_j[g2]
    n1 <- n_j[g1]
    n2 <- n_j[g2]
    
    # Apply the mathematical formula of the Marascuilo procedure
    dif_abs <- abs(p1 - p2)
    error_estandar <- sqrt((p1 * (1 - p1) / n1) + (p2 * (1 - p2) / n2))
    m_jj <- sqrt(chi_critico) * error_estandar
    
    # Construct the output row for this specific comparison
    data.frame(
      Pair = paste(g1, "vs", g2),
      Absolute_Diff = round(dif_abs, 4),
      Critical_Range = round(m_jj, 4),
      Significance = ifelse(dif_abs > m_jj, "Significant", "Not Significant"),
      stringsAsFactors = FALSE
    )
  })
  
  return(resultados)
}

#' Marascuilo Test Plot
#'
#' @param resultados A data.frame generated by the marascuilo_test() function.
#'
#' @return A ggplot object visualizing the pairwise comparisons.
#' @export
#' @import ggplot2
plot_marascuilo <- function(resultados) {
  
  # Initialize plot: mapping differences to bars and significance to fill color
  grafico <- ggplot(resultados, aes(x = Pair, y = Absolute_Diff, fill = Significance)) +
    geom_col(alpha = 0.8) +
    
    # Overlay critical range as points (crosses) to visually compare against the bars
    geom_point(aes(y = Critical_Range), color = "black", size = 4, shape = 4, show.legend = FALSE) +
    
    # Define custom colors for the significance levels in the legend
    scale_fill_manual(
      name = "Test Conclusion:",
      values = c("Significant" = "#b37079", "Not Significant" = "#02d963")
    ) +
    
    # Set descriptive titles, subtitle, and axis labels
    labs(
      title = "Marascuilo Test Results",
      subtitle = "Absolute Difference (bars) vs Critical Range (black crosses)",
      x = "Compared Pairs",
      y = "Absolute Difference in Proportions"
    ) +
    
    # Apply a clean, minimalist background theme
    theme_minimal()
  
  return(grafico)
}